name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}
      
    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        cmake -B build
        cmake --build build --parallel 2 --verbose
    
    - name: test
      run: |
        ctest --test-dir build --verbose --output-on-failure --rerun-failed 
