name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: g2tmpl
        submodules: true

    - name: build
      run: |
        cd g2tmpl
        mkdir build 
        cd build
        cmake ..
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2tmpl/build

